### ISSUE TITLE
Direction results

### ISSUE THREAD

**Issue by lucyewright** [fac-15/events-api#20]
Your directions are fine if you know an area but just being told:
Walk to _'this'_ road.... more details would be great!
Walk to _'POSTCODE'_ ..... if you guys can navigate by postcode i'm super envious! Again a little more help would be great for someone like me who is terrible at finding locations I don't know!!
![](https://media.giphy.com/media/t68gTcuEpHOiA/giphy.gif)

**Comment by jcharnley** [comment]
stretch goals
